image:
  repository: "" # e.g. <aws_account_id>.dkr.ecr.<region>.amazonaws.com/lesson-7-node-app
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  port: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  # Environment variables for the app (migrated from topic 4)
  POSTGRES_HOST: ""
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  PORT: "8000"

resources: {}
