apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "node-app.name" . }}
    helm.sh/chart: {{ include "node-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
